/*--------------------------------------------------------------------------------------------------------------
 * Este script SQL tem como objetivo principal extrair e organizar dados detalhados sobre ocorrências
 *  relacionadas à crimes violentos
 --------------------------------------------------------------------------------------------------------------*/
SELECT  OCO.numero_ocorrencia,  -- SELECIONA O NÚMERO DA OCORRÊNCIA
OCO.data_hora_fato,  -- SELECIONA A DATA E HORA DO FATO
OCO.natureza_codigo,  -- SELECIONA O CÓDIGO DA NATUREZA PRINCIPAL DO FATO
OCO.natureza_descricao,  -- SELECIONA A DESCRIÇÃO DA NATUREZA PRINCIPAL DO FATO
OCO.natureza_consumado, -- SELECIONA A DESCRIÇÃO DE CONSUMAÇÃO DA NATUREZA
OCO.natureza_secundaria1_descricao,  -- SELECIONA A  DESCRIÇÃO DA PRIMEIRA NATUREZA SECUNDÁRIA
OCO.natureza_secundaria1_consumado , -- SELECIONA A DESCRIÇÃO DE CONSUMAÇÃO DA PRIMEIRA NATUREZA SECUNDÁRIA
OCO.natureza_secundaria2_descricao,  -- SELECIONA A DESCRIÇÃO DA SEGUNDA NATUREZA SECUNDÁRIA
OCO.natureza_secundaria2_consumado, -- SELECIONA A DESCRIÇÃO DE CONSUMAÇÃO DA SEGUNDA NATUREZA SECUNDÁRIA
OCO.natureza_secundaria3_descricao,  -- SELECIONA A DESCRIÇÃO DA TERCEIRA NATUREZA SECUNDÁRIA
OCO.natureza_secundaria3_consumado, -- SELECIONA A DESCRIÇÃO DE CONSUMAÇÃO DA TERCEIRA NATUREZA SECUNDÁRIA
OCO.numero_latitude,  -- SELECIONA A LATITUDE DO FATO
OCO.numero_longitude,  -- SELECIONA A LONGITUDE DO FATO
OCO.nome_municipio,  -- SELECIONA O NOME DO MUNICÍPIO DO FATO
OCO.nome_bairro,  -- SELECIONA O BAIRRO DO FATO
OCO.numero_endereco,  -- SELECIONA O NÚMERO DO ENDEREÇO DO FATO
OCO.logradouro_nome,  -- SELECIONA O NOME DO LOGRADOURO DO FATO
OCO.unidade_responsavel_registro_nome,  -- SELECIONA O NOME DA UNIDADE RESPONSÁVEL PELO REGISTRO
OCO.unidade_area_militar_nome,  -- SELECIONA O NOME DA UNIDADE DA ÁREA MILITAR
OCO.digitador_sigla_orgao  -- SELECIONA A SIGLA DO ÓRGÃO DO DIGITADOR
FROM tb_ocorrencia OCO  -- TABELA DE OCORRÊNCIAS ALIAS "OCO"
WHERE YEAR(data_hora_fato) = :ANO  -- PROMPT PARA FILTRAR ANO DO FATO
AND MONTH(OCO.data_hora_fato) BETWEEN :MESINICIAL AND :MESFINAL  -- PROMPT PARA FILTRAR MESES INICIAL E FINAL
AND OCO.digitador_id_orgao IN (0, 1)  -- FILTRA PELOS ID DE ÓRGÃOS DOS DIGITADORES (PM E PC)
AND OCO.ind_estado ='F'
AND OCO.ocorrencia_uf = 'MG'  -- FILTRA OCORRÊNCIAS DO ESTADO DE MINAS GERAIS
AND ( 
        OCO.natureza_codigo IN ('B01121', 'B01148', 'C01157', 'C01159', 'D01213', 'D01217', 'B01129', 'B02001', 'C01158')  -- FILTRA PELA NATUREZA PRINCIPAL SENDO ELAS: HOMICÍDIO, SEQUESTRO E CÁRCERE PRIVADO, ROUBO, EXTROSÃO MEDIANTE SEQUESTRO, ESTUPRO, ESTUPRO DE VULNERÁVEL, LESÃO CORPORAL SEGUIDA DE MORTE, TORTURA, EXTORSÃO
        OR OCO.natureza_secundaria1_codigo IN ('B01121', 'B01148', 'C01157', 'C01159', 'D01213', 'D01217', 'B01129', 'B02001', 'C01158')  -- FILTRA PELO CÓDIGO DA PRIMEIRA NATUREZA SECUNDÁRIA SENDO ELAS: HOMICÍDIO, SEQUESTRO E CÁRCERE PRIVADO, ROUBO, EXTROSÃO MEDIANTE SEQUESTRO, ESTUPRO, ESTUPRO DE VULNERÁVEL, LESÃO CORPORAL SEGUIDA DE MORTE, TORTURA, EXTORSÃO
        OR OCO.natureza_secundaria2_codigo IN ('B01121', 'B01148', 'C01157', 'C01159', 'D01213', 'D01217', 'B01129', 'B02001', 'C01158')  -- FILTRA PELO CÓDIGO DA SEGUNDA NATUREZA SECUNDÁRIA SENDO ELAS: HOMICÍDIO, SEQUESTRO E CÁRCERE PRIVADO, ROUBO, EXTROSÃO MEDIANTE SEQUESTRO, ESTUPRO, ESTUPRO DE VULNERÁVEL, LESÃO CORPORAL SEGUIDA DE MORTE, TORTURA, EXTORSÃO
        OR OCO.natureza_secundaria3_codigo IN ('B01121', 'B01148', 'C01157', 'C01159', 'D01213', 'D01217', 'B01129', 'B02001', 'C01158')  -- FILTRA PELO CÓDIGO DA TERCEIRA NATUREZA SECUNDÁRIA SENDO ELAS: HOMICÍDIO, SEQUESTRO E CÁRCERE PRIVADO, ROUBO, EXTROSÃO MEDIANTE SEQUESTRO, ESTUPRO, ESTUPRO DE VULNERÁVEL, LESÃO CORPORAL SEGUIDA DE MORTE, TORTURA, EXTORSÃO
        )
AND OCO.nome_municipio LIKE '%XXXX%'  -- FILTRO PELO NOME DO MUNICÍPIO. SE PREFERIR USE : --and OCO.codigo_municipio = 00  --  FILTRO PELO CÓDIGO DO MUNICÍPIO 

